[package]
name = "mystig-next"
version = "0.1.0"
authors = ["taskie <t@skie.jp>"]

[dependencies]
hlua = "0.3"

[dependencies.sdl2]
version = "0.30"
default-features = false
features = ["ttf", "image", "gfx", "mixer"]
